### ISSUE TITLE
你好，配置完cookie运行出现以下错误

### ISSUE THREAD

**Issue by huakair** [KotoriMinami/qinglong-sign#13]
Traceback (most recent call last):
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in <module>
    res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n'
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 150, in main
    music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")}
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 150, in <dictcomp>
    music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")}
IndexError: list index out of range

请大佬帮帮忙

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 180, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 150, in main music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")} File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 150, in music_cookie = {item.split("=")[0]: item.split("=")[1] for item in cookie.split("; ")} IndexError: list index out of range
> 
> 请大佬帮帮忙

呃.. 你配置里面只保留你的cookie，把示例那个删掉试试

**Comment by huakair** [comment]
你好，配置的cookie示例已经删了，但是还是出现这样的错误，JSON检验是正确的

**Comment by huakair** [comment]
你好，配置的cookie示例已经删了，但是还是出现这样的错误，JSON检验是正确的``

**Comment by KotoriMinami** [comment]
> 你好，配置的cookie示例已经删了，但是还是出现这样的错误，JSON检验是正确的

方便把你抓的cookie放上来看看吗, 关键内容记得去掉

**Comment by huakair** [comment]
你好，可以加个Q发嘛

**Comment by huakair** [comment]
![WW61D9U}R5A8C~42}6)~FY7](https://user-images.githubusercontent.com/87841078/169215018-3419eb99-91af-412b-a900-03565a112ad1.png)

**Comment by KotoriMinami** [comment]
> ![WW61D9U}R5A8C~42}6)~FY7](https://user-images.githubusercontent.com/87841078/169215018-3419eb99-91af-412b-a900-03565a112ad1.png)

看起来是这个有问题.. 你留个q吧 我加你帮你看看

**Comment by huakair** [comment]
255376668

**Comment by huakair** [comment]
谢谢～

**Comment by zp9999** [comment]
请问，这个怎么解决的，我也是这种情况
