### ISSUE TITLE
这几天突然报错了，好像是JSON格式的问题

### ISSUE THREAD

**Issue by YiCarlos** [KotoriMinami/qinglong-sign#22]
报错如下：
  Traceback (most recent call last):
  File "/ql/scripts/copartner.py", line 178, in <module>
    res = Copartner(_check_item).main()
  File "/ql/scripts/copartner.py", line 153, in main
    music_data, user_name = self.valid(session)
  File "/ql/scripts/copartner.py", line 127, in valid
    data = content.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KotoriMinami** [comment]
问题已修复，更新库即可 #20
