### ISSUE TITLE
你好，更换服务器后出现如下错误

### ISSUE THREAD

**Issue by huakair** [KotoriMinami/qinglong-sign#24]
Traceback (most recent call last):
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 190, in <module>
    res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n'
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 168, in main
    self.sign(session, music_data, msg)
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 101, in sign
    "params": self.get_params({
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 83, in get_params
    return aes_encrypt(aes_encrypt(enc_text, self.g, self.iv), self.i, self.iv)
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 27, in aes_encrypt
    encryptor = AES.new(to_16(key), AES.MODE_CBC, to_16(iv))
  File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

你好，旧服务器要到期了，重新拉取之后，新服务器执行出现错误以上，但是在旧服务器执行成功之后再到新服务器执行发现成功运行，大佬帮我看看是什么原因

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 190, in res = f'{res}账号{index + 1}：\n{Copartner(item).main()}\n' File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 168, in main self.sign(session, music_data, msg) File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 101, in sign "params": self.get_params({ File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 83, in get_params return aes_encrypt(aes_encrypt(enc_text, self.g, self.iv), self.i, self.iv) File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 27, in aes_encrypt encryptor = AES.new(to_16(key), AES.MODE_CBC, to_16(iv)) File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new return AESCipher(key, *args, **kwargs) File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in **init** blockalgo.BlockAlgo.**init**(self, _AES, key, *args, **kwargs) File "/usr/local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in **init** self._cipher = factory.new(key, *args, **kwargs) SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
> 
> 你好，旧服务器要到期了，重新拉取之后，新服务器执行出现错误以上，但是在旧服务器执行成功之后再到新服务器执行发现成功运行，大佬帮我看看是什么原因

依赖库改为这个试试 `pycryptodome`
