### ISSUE TITLE
大佬这道这个报错是什么原因吗

### ISSUE THREAD

**Issue by SneakyTUG** [KotoriMinami/qinglong-sign#34]
Traceback (most recent call last):
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 178, in <module>
    all_data = json.loads(f.read())
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 3 (char 2178)

**Comment by KotoriMinami** [comment]
> Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.py", line 178, in all_data = json.loads(f.read()) File "/usr/local/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 7 column 3 (char 2178)

应该是你json文件格式不对，你可以复制全文去`https://www.bejson.com/`校验一下看看
