### ISSUE TITLE
大佬您看下这是怎么回事 日志如下，抓了好几次都登陆不上

### ISSUE THREAD

**Issue by Thomas-xX** [KotoriMinami/qinglong-sign#38]
## 开始执行... 2024-02-14 23:13:36

账号1：
帐号信息: 登录验证异常,错误信息: HTTPConnectionPool(host='interface.music.163.com', port=80): Max retries exceeded with url: /api/music/partner/daily/task/get (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xb5f4b778>: Failed to resolve 'interface.music.163.com' ([Errno -3] Try again)"))
cookie信息: Cookie 可能过期

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.swap.py", line 184, in <module>
    send('网易音乐合伙人', res)
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/notify.py", line 526, in send
    text = one() if hitokoto else ""
  File "/ql/data/scripts/KotoriMinami_qinglong-sign/notify.py", line 487, in one
    res = requests.get(url).json()
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)"))

## 执行结束... 2024-02-14 23:13:49  耗时 13 秒

**Comment by KotoriMinami** [comment]
> ## 开始执行... 2024-02-14 23:13:36
> 账号1： 帐号信息: 登录验证异常,错误信息: HTTPConnectionPool(host='interface.music.163.com', port=80): Max retries exceeded with url: /api/music/partner/daily/task/get (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xb5f4b778>: Failed to resolve 'interface.music.163.com' ([Errno -3] Try again)")) cookie信息: Cookie 可能过期
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn sock = connection.create_connection( File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Try again
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request raise new_e File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect self.sock = sock = self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn raise NameResolutionError(self.host, self, e) from e urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)"))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.swap.py", line 184, in send('网易音乐合伙人', res) File "/ql/data/scripts/KotoriMinami_qinglong-sign/notify.py", line 526, in send text = one() if hitokoto else "" File "/ql/data/scripts/KotoriMinami_qinglong-sign/notify.py", line 487, in one res = requests.get(url).json() File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)"))
> 
> ## 执行结束... 2024-02-14 23:13:49 耗时 13 秒

老哥你是音乐合伙人吗

**Comment by Pandolar** [comment]
> > ## 开始执行... 2024-02-14 23:13:36
> > 账号1： 帐号信息: 登录验证异常,错误信息: HTTPConnectionPool(host='interface.music.163.com', port=80): Max retries exceeded with url: /api/music/partner/daily/task/get (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xb5f4b778>: Failed to resolve 'interface.music.163.com' ([Errno -3] Try again)")) cookie信息: Cookie 可能过期
> > Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn sock = connection.create_connection( File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Try again
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request raise new_e File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect self.sock = sock = self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn raise NameResolutionError(self.host, self, e) from e urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)"))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/ql/data/scripts/KotoriMinami_qinglong-sign/sign_copartner.swap.py", line 184, in send('网易音乐合伙人', res) File "/ql/data/scripts/KotoriMinami_qinglong-sign/notify.py", line 526, in send text = one() if hitokoto else "" File "/ql/data/scripts/KotoriMinami_qinglong-sign/notify.py", line 487, in one res = requests.get(url).json() File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xb5f2be98>: Failed to resolve 'v1.hitokoto.cn' ([Errno -3] Try again)"))
> > ## 执行结束... 2024-02-14 23:13:49 耗时 13 秒
> 
> 老哥你是音乐合伙人吗

直击灵魂的拷问

**Comment by guan1112344** [comment]
一句话干沉默所有人了
